### ISSUE TITLE
Multiple anime titles download don't work

### ISSUE THREAD

**Issue by Lukyzzz** [jmir1/aniyomi#547]
### Steps to reproduce

1 - Select multiple animes titles (from any extension, I've tried AnimesVision, Haninetv .... Etc) on any category
2 - Click/Tap on the download icon on the bottom, between "Set categories" and "Mark as read"

### Expected behavior

It should download the animes titles selected

### Actual behavior

Nothing happens, really, nothing

Already tried cleaning everything and reinstalled but nothing

If I open the titles and try to download the episodes manually, it works just fine

And the option to download multiple *mangas* titles by selecting it, it's working just fine

It's just the anime tab

### Aniyomi version

0.12.3.6

### Android version

Android 12 (but it was like that on Android 11 too)

### Device

Samsung Galaxy M62

### Other details

I'm using the preview version
App version: 0.12.3.6-4513 (standard, 98b7e1dbe, 72, 2022-04-01T17:57Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.M625FXXU2BVC3
Device brand: samsung
Device manufacturer: samsung
Device name: m62
Device model: SM-M625F
Device product name: m62xx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Fixed in latest beta

**Comment by Lukyzzz** [comment]
Still the same, is it going to be fix on the next update ?
All the other options of the bottom bar work, it's just the" download unread chapters"

**Comment by Quickdesh** [comment]
It's fixed in the beta version. I don't think the stable will get a new update in a while.

**Comment by Lukyzzz** [comment]
I was waiting for the update that would fix this but it never came, can I download manually ?

**Comment by Quickdesh** [comment]
https://github.com/jmir1/aniyomi-mpv-beta/releases/latest
